eyetracker:
    address: 100.1.1.1
    dot_size: 0.1
    options:
        active_eye: left
        automatic_calibration_pacing: 1000
        autothreshold_click: true
        autothreshold_repeat: true
        binocular_enabled: false
        calibration_type: HV9
        enable_automatic_calibration: true
        enable_camera_position_detect: true
        enable_search_limits: true
        file_event_filter: LEFT,RIGHT,FIXATION,SACCADE,BLINK,MESSAGE,BUTTON,INPUT
        heuristic_filter: 2
        link_event_filter: LEFT,RIGHT,FIXATION,SACCADE,BLINK,BUTTON
        link_sample_data: LEFT,RIGHT,GAZE,GAZERES,AREA,STATUS,HTARGET
        pupil_size_diameter: true
        sample_rate: 1000
        track_search_limits: true
        x_gaze_constraint: AUTO
        y_gaze_constraint: AUTO
monitor:
    distance: 65
    gamma: 1
    name: default
    width: 53
mouse:
    visible: false
mri:
    TA: 2.0
    TR: 2.0
    simulate: false
    skip: 0
    sound: false
    sync: t
    volumes: 10
preferences:
    general:
        audioLib: PTB
        units: deg
window:
    color:
    - 0
    - 0
    - 0
    fullscr: false
    pos:
    - 0
    - 0
    screen: 1
    size:
    - 1920
    - 1080
    waitBlanking: true
